# Generated by Django 6.0.6 on 2026-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_city_customer_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
